all:
  vars:
    ansible_connection: ssh
  hosts:
    ceres.lan:
      ansible_host: 10.11.12.171
    deimos.lan:
      ansible_host: 10.11.12.48
    nas.lan:
      ansible_host: 10.11.12.16
  children:
    kube_control_plane:
      hosts:
        ceres.lan:
    kube_node:
      hosts:
        ceres.lan:
        deimos.lan:
        nas.lan:
    etcd:
      hosts:
        ceres.lan:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
