all:
  # Ansible connection settings.
  vars:
    # Explicitly set the connection type to the node servers.
    ansible_connection: ssh

    # Explicitly set using root user, to not require sudo configuration.
    # You can comment out this to use a regular user for connecting.
#    ansible_user: root
  hosts:
    lan-master-01.lan:
      ansible_host: 10.11.12.171
    lan-worker-01.lan:
      ansible_host: 10.11.12.121
    lan-worker-02.lan:
      ansible_host: 10.11.12.117
  children:
    kube_control_plane:
      hosts:
        lan-master-01.lan:
    kube_node:
      hosts:
        lan-master-01.lan:
        lan-worker-01.lan:
        lan-worker-02.lan:
    etcd:
      hosts:
        lan-master-01.lan:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
