---
# handlers file for base
- name: restart_systemd-sysctl
  service:
    name: systemd-sysctl
    state: restarted

- name: reboot
  reboot:
    msg: "reboot initiated by ansible"

- name: refresh lvm cache
  ansible.builtin.command:
    cmd: pvscan --cache
  changed_when: false