all:
  vars:
    ansible_connection: ssh
  hosts:
    core.lan:
      ansible_host: 10.11.12.122
  children:
    kube_control_plane:
      hosts:
        core.lan:
    kube_node:
      hosts:
        core.lan:
    etcd:
      hosts:
        core.lan:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
